// GROUNDING — verbatim self-descriptions of recommended skills, fetched from
// each skill's live repo by pipeline/ground_recs.py. ok:true entries quote the
// skill's OWN words (source + blob sha + date). ok:false = could not verify —
// shown as 'unverified' in the UI, never fabricated. Regenerate, don't hand-edit.
const GROUNDING = {
  "AGENTS.md": {
    "name": "AGENTS.md",
    "url": "https://github.com/agentsmd/agents.md",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "AI-Research-SKILLs": {
    "name": "AI-Research-SKILLs",
    "url": "https://github.com/Orchestra-Research/AI-Research-SKILLs",
    "type": "skill",
    "installable": true,
    "repo": "Orchestra-Research/AI-Research-SKILLs",
    "ok": true,
    "path": "README.md",
    "sha": "2d58d4f",
    "source": "GitHub repo description",
    "quote": "Comprehensive open-source library of AI research and engineering skills for any AI model. Package the skills and your claude code/codex/gemini agent will be an AI research agent with full horsepower. Maintained by Orchestra Research.",
    "fetched": "2026-07-29"
  },
  "Anthropic-Cybersecurity-Skills": {
    "name": "Anthropic-Cybersecurity-Skills",
    "url": "https://github.com/mukul975/Anthropic-Cybersecurity-Skills",
    "type": "skill",
    "installable": true,
    "repo": "mukul975/Anthropic-Cybersecurity-Skills",
    "ok": true,
    "path": "README.md",
    "sha": "8f51d22",
    "source": "GitHub repo description",
    "quote": "817 structured cybersecurity skills for AI agents · Mapped to 6 frameworks: MITRE ATT&CK, NIST CSF 2.0, MITRE ATLAS, D3FEND, NIST AI RMF & MITRE F3 (Fight Fraud) · agentskills.io standard · Works with Claude Code, GitHub Copilot, Codex CLI, Cursor, Gemini CLI & 20+ platforms · 29 security domains · Apache 2.0",
    "fetched": "2026-07-29"
  },
  "Awesome-AI-Agents-for-Healthcare": {
    "name": "Awesome-AI-Agents-for-Healthcare",
    "url": "https://github.com/AgenticHealthAI/Awesome-AI-Agents-for-Healthcare",
    "type": "skill",
    "installable": true,
    "repo": "AgenticHealthAI/Awesome-AI-Agents-for-Healthcare",
    "ok": true,
    "path": "README.md",
    "sha": "0cb3d5b",
    "source": "GitHub repo description",
    "quote": "Latest Advances on Agentic AI & AI Agents for Healthcare",
    "fetched": "2026-07-29"
  },
  "CLAUDE.md": {
    "name": "CLAUDE.md",
    "url": "https://docs.claude.com/en/docs/claude-code/memory",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Claude-Code-Game-Studios": {
    "name": "Claude-Code-Game-Studios",
    "url": "https://github.com/Donchitos/Claude-Code-Game-Studios",
    "type": "skill",
    "installable": true,
    "repo": "Donchitos/Claude-Code-Game-Studios",
    "ok": true,
    "path": "README.md",
    "sha": "c08cec9",
    "source": "GitHub repo description",
    "quote": "Turn Claude Code into a full game dev studio — 49 AI agents, 72 workflow skills, and a complete coordination system mirroring real studio hierarchy.",
    "fetched": "2026-07-29"
  },
  "EU AI Act": {
    "name": "EU AI Act",
    "url": "https://artificialintelligenceact.eu/",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Global Responsible AI in Healthcare": {
    "name": "Global Responsible AI in Healthcare",
    "url": "https://github.com/nliulab/Global-Responsible-AI",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Guardrails AI": {
    "name": "Guardrails AI",
    "url": "https://github.com/guardrails-ai/guardrails",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Humanizer-zh": {
    "name": "Humanizer-zh",
    "url": "https://github.com/op7418/Humanizer-zh",
    "type": "skill",
    "installable": true,
    "repo": "op7418/Humanizer-zh",
    "ok": true,
    "path": "SKILL.md",
    "sha": "3b39d9a",
    "source": "SKILL.md description",
    "quote": "去除文本中的 AI 生成痕迹。适用于编辑或审阅文本，使其听起来更自然、更像人类书写。 基于维基百科的\"AI 写作特征\"综合指南。检测并修复以下模式：夸大的象征意义、 宣传性语言、以 -ing 结尾的肤浅分析、模糊的归因、破折号过度使用、三段式法则、 AI 词汇、否定式排比、过多的连接性短语。",
    "fetched": "2026-07-29"
  },
  "Llama Guard / PurpleLlama": {
    "name": "Llama Guard / PurpleLlama",
    "url": "https://github.com/meta-llama/PurpleLlama",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "MITRE ATT&CK Navigator": {
    "name": "MITRE ATT&CK Navigator",
    "url": "https://github.com/mitre-attack/attack-navigator",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "NIST AI Risk Management Framework": {
    "name": "NIST AI Risk Management Framework",
    "url": "https://www.nist.gov/itl/ai-risk-management-framework",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "NeMo Guardrails": {
    "name": "NeMo Guardrails",
    "url": "https://github.com/NVIDIA-NeMo/Guardrails",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "OWASP Top 10 for LLM Apps": {
    "name": "OWASP Top 10 for LLM Apps",
    "url": "https://github.com/OWASP/www-project-top-10-for-large-language-model-applications",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "OpenClaw-Medical-Skills": {
    "name": "OpenClaw-Medical-Skills",
    "url": "https://github.com/FreedomIntelligence/OpenClaw-Medical-Skills",
    "type": "skill",
    "installable": true,
    "repo": "FreedomIntelligence/OpenClaw-Medical-Skills",
    "ok": true,
    "path": "README.md",
    "sha": "5eb30e2",
    "source": "GitHub repo description",
    "quote": "The largest open-source medical AI skills library for OpenClaw🦞.",
    "fetched": "2026-07-29"
  },
  "Rebuff": {
    "name": "Rebuff",
    "url": "https://github.com/protectai/rebuff",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Responsible AI Toolbox": {
    "name": "Responsible AI Toolbox",
    "url": "https://github.com/microsoft/responsible-ai-toolbox",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "Skill_Seekers": {
    "name": "Skill_Seekers",
    "url": "https://github.com/yusufkaraaslan/Skill_Seekers",
    "type": "skill",
    "installable": true,
    "repo": "yusufkaraaslan/Skill_Seekers",
    "ok": true,
    "path": "README.md",
    "sha": "056157c",
    "source": "GitHub repo description",
    "quote": "Convert documentation websites, GitHub repositories, and PDFs into Claude AI skills with automatic conflict detection",
    "fetched": "2026-07-29"
  },
  "academic-research-skills": {
    "name": "academic-research-skills",
    "url": "https://github.com/Imbad0202/academic-research-skills",
    "type": "skill",
    "installable": true,
    "repo": "Imbad0202/academic-research-skills",
    "ok": true,
    "path": "README.md",
    "sha": "b3846a0",
    "source": "GitHub repo description",
    "quote": "Academic Research Skills for Claude Code: research → write → review → revise → finalize",
    "fetched": "2026-07-29"
  },
  "ai-governance-framework-tools": {
    "name": "ai-governance-framework-tools",
    "url": "https://github.com/BinaryVerseAI/ai-governance-framework-tools",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "algorithmic-art": {
    "name": "algorithmic-art",
    "url": "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/algorithmic-art/SKILL.md",
    "sha": "634f6fa",
    "source": "SKILL.md description",
    "quote": "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists' work to avoid copyright violations.",
    "fetched": "2026-07-29"
  },
  "awesome-agent-skills": {
    "name": "awesome-agent-skills",
    "url": "https://github.com/VoltAgent/awesome-agent-skills",
    "type": "skill",
    "installable": true,
    "repo": "VoltAgent/awesome-agent-skills",
    "ok": true,
    "path": "README.md",
    "sha": "eb5d909",
    "source": "GitHub repo description",
    "quote": "A curated collection of 1000+ agent skills from official dev teams and the community, compatible with Claude Code, Codex, Gemini CLI, Cursor, and more.",
    "fetched": "2026-07-29"
  },
  "awesome-ai-agent-governance": {
    "name": "awesome-ai-agent-governance",
    "url": "https://github.com/systempromptio/awesome-ai-agent-governance",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "awesome-ai-governance": {
    "name": "awesome-ai-governance",
    "url": "https://github.com/Myr-Aya/awesome-ai-governance",
    "type": "governance",
    "installable": false,
    "ok": false,
    "reason": "reference-only (no installable skill repo)"
  },
  "awesome-claude-code": {
    "name": "awesome-claude-code",
    "url": "https://github.com/hesreallyhim/awesome-claude-code",
    "type": "skill",
    "installable": true,
    "repo": "hesreallyhim/awesome-claude-code",
    "ok": true,
    "path": "README.md",
    "sha": "0df5077",
    "source": "GitHub repo description",
    "quote": "A hand-picked collection of the finest of resources for the most awesome of agents, Claude Code, the undisputed champion of coding companions, from the unstoppable team at Anthropic PBC. A delectable showcase of top tier skills, ambidextrous agents, scintillating status lines, top notch developer tooling, and also we have plugins",
    "fetched": "2026-07-29"
  },
  "awesome-medical-imaging-agents": {
    "name": "awesome-medical-imaging-agents",
    "url": "https://github.com/Nanboy-Ronan/awesome-medical-imaging-agents",
    "type": "skill",
    "installable": true,
    "repo": "Nanboy-Ronan/awesome-medical-imaging-agents",
    "ok": true,
    "path": "README.md",
    "sha": "001d482",
    "source": "GitHub repo description",
    "quote": "Awesome list for medical imaging agents: radiology agents, pathology agents, segmentation agents, medical VLM agents, self-evolving agents, benchmarks, datasets, tools, and papers.",
    "fetched": "2026-07-29"
  },
  "book-to-skill": {
    "name": "book-to-skill",
    "url": "https://github.com/virgiliojr94/book-to-skill",
    "type": "skill",
    "installable": true,
    "repo": "virgiliojr94/book-to-skill",
    "ok": true,
    "path": "SKILL.md",
    "sha": "e224b8f",
    "source": "SKILL.md description",
    "quote": "Converts books and documents (PDF, EPUB, DOCX, HTML, Markdown, plain text, RTF, MOBI/AZW with Calibre) into structured agent skills, extracting frameworks, mental models, principles, techniques, and anti-patterns. Use when the user wants to study a document through GitHub Copilot CLI, Amp, or Claude Code, apply an author's frameworks while working, or build a reusable knowledge base from a file.",
    "fetched": "2026-07-29"
  },
  "brand-guidelines": {
    "name": "brand-guidelines",
    "url": "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/brand-guidelines/SKILL.md",
    "sha": "47c72c6",
    "source": "SKILL.md description",
    "quote": "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.",
    "fetched": "2026-07-29"
  },
  "canvas-design": {
    "name": "canvas-design",
    "url": "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/canvas-design/SKILL.md",
    "sha": "9f63fee",
    "source": "SKILL.md description",
    "quote": "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.",
    "fetched": "2026-07-29"
  },
  "claude-api": {
    "name": "claude-api",
    "url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/claude-api/SKILL.md",
    "sha": "6ddbf0b",
    "source": "SKILL.md description",
    "quote": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
    "fetched": "2026-07-29"
  },
  "claude-code-infrastructure-showcase": {
    "name": "claude-code-infrastructure-showcase",
    "url": "https://github.com/diet103/claude-code-infrastructure-showcase",
    "type": "skill",
    "installable": true,
    "repo": "diet103/claude-code-infrastructure-showcase",
    "ok": true,
    "path": "README.md",
    "sha": "9c54933",
    "source": "GitHub repo description",
    "quote": "Examples of my Claude Code infrastructure with skill auto-activation, hooks, and agents",
    "fetched": "2026-07-29"
  },
  "claude-code-tips": {
    "name": "claude-code-tips",
    "url": "https://github.com/ykdojo/claude-code-tips",
    "type": "skill",
    "installable": true,
    "repo": "ykdojo/claude-code-tips",
    "ok": true,
    "path": "README.md",
    "sha": "f60cf84",
    "source": "GitHub repo description",
    "quote": "40+ tips for getting the most out of Claude Code, from basics to advanced - includes a custom status line script and Claude Code running itself in a container. Also includes the dx plugin: skills for everyday dev workflows.",
    "fetched": "2026-07-29"
  },
  "claude-seo": {
    "name": "claude-seo",
    "url": "https://github.com/AgriciDaniel/claude-seo",
    "type": "skill",
    "installable": true,
    "repo": "AgriciDaniel/claude-seo",
    "ok": true,
    "path": "README.md",
    "sha": "724cf4f",
    "source": "GitHub repo description",
    "quote": "Universal SEO skill for Claude Code. 25 sub-skills + 18 sub-agents covering technical SEO, E-E-A-T, schema, GEO/AEO, backlinks, local SEO, maps intelligence, semantic clustering, e-commerce SEO, international SEO, Google APIs, and PDF/Excel reporting. Optional DataForSEO, Firecrawl, and Banana extensions.",
    "fetched": "2026-07-29"
  },
  "doc-coauthoring": {
    "name": "doc-coauthoring",
    "url": "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/doc-coauthoring/SKILL.md",
    "sha": "a5a6983",
    "source": "SKILL.md description",
    "quote": "Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.",
    "fetched": "2026-07-29"
  },
  "docx": {
    "name": "docx",
    "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/docx/SKILL.md",
    "sha": "fb954a4",
    "source": "SKILL.md description",
    "quote": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
    "fetched": "2026-07-29"
  },
  "frontend-design": {
    "name": "frontend-design",
    "url": "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/frontend-design/SKILL.md",
    "sha": "decdff4",
    "source": "SKILL.md description",
    "quote": "Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don't read as templated defaults.",
    "fetched": "2026-07-29"
  },
  "geo-seo-claude": {
    "name": "geo-seo-claude",
    "url": "https://github.com/zubair-trabzada/geo-seo-claude",
    "type": "skill",
    "installable": true,
    "repo": "zubair-trabzada/geo-seo-claude",
    "ok": true,
    "path": "README.md",
    "sha": "0460ae2",
    "source": "GitHub repo description",
    "quote": "GEO-first SEO skill for Claude Code. Comprehensive AI search optimization for any website — citability scoring, AI crawler analysis, brand authority, schema markup, platform-specific optimization, and PDF reports.  If you want learn how to sell this to real businesses, check out the skool community",
    "fetched": "2026-07-29"
  },
  "graphify": {
    "name": "graphify",
    "url": "https://github.com/Graphify-Labs/graphify",
    "type": "skill",
    "installable": true,
    "repo": "Graphify-Labs/graphify",
    "ok": true,
    "path": "README.md",
    "sha": "a4f188f",
    "source": "GitHub repo description",
    "quote": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "fetched": "2026-07-29"
  },
  "hallmark": {
    "name": "hallmark",
    "url": "https://github.com/Nutlope/hallmark",
    "type": "skill",
    "installable": true,
    "repo": "Nutlope/hallmark",
    "ok": true,
    "path": "README.md",
    "sha": "a615a80",
    "source": "GitHub repo description",
    "quote": "Anti-AI-slop design skill for Claude Code, Cursor, and Codex.",
    "fetched": "2026-07-29"
  },
  "healthcare-agents": {
    "name": "healthcare-agents",
    "url": "https://github.com/ajhcs/healthcare-agents",
    "type": "skill",
    "installable": true,
    "repo": "ajhcs/healthcare-agents",
    "ok": true,
    "path": "README.md",
    "sha": "9290ec6",
    "source": "GitHub repo description",
    "quote": "Portable prompt and SKILL.md pack with 51 specialist AI agents for US healthcare administration workflows.",
    "fetched": "2026-07-29"
  },
  "huashu-design": {
    "name": "huashu-design",
    "url": "https://github.com/alchaincyf/huashu-design",
    "type": "skill",
    "installable": true,
    "repo": "alchaincyf/huashu-design",
    "ok": true,
    "path": "SKILL.md",
    "sha": "0c2edbe",
    "source": "SKILL.md description",
    "quote": "花叔Design——用HTML做高保真原型、幻灯片、动画、可视化与专家评审。任何新设计100%先出三个方向初稿给用户选（指定风格/品牌也不豁免），选定后才执行。触发词：做原型、PPT、幻灯片、动画、设计风格、评审、做个HTML页面、UI mockup、导出MP4/GIF、做个好看的。生产级Web App/需后端的系统不适用。",
    "fetched": "2026-07-29"
  },
  "humanizer": {
    "name": "humanizer",
    "url": "https://github.com/blader/humanizer",
    "type": "skill",
    "installable": true,
    "repo": "blader/humanizer",
    "ok": true,
    "path": "SKILL.md",
    "sha": "0a40275",
    "source": "SKILL.md description",
    "quote": "Remove signs of AI-generated writing from text. Use when editing or reviewing text to make it sound more natural and human-written. Based on Wikipedia's comprehensive \"Signs of AI writing\" guide. Detects and fixes patterns including: inflated symbolism, promotional language, superficial -ing analyses, vague attributions, em dash overuse, rule of three, AI vocabulary words, passive voice, negative parallelisms, and filler phrases.",
    "fetched": "2026-07-29"
  },
  "informed-patient": {
    "name": "informed-patient",
    "url": "https://github.com/DrCatHicks/informed-patient",
    "type": "skill",
    "installable": true,
    "repo": "DrCatHicks/informed-patient",
    "ok": true,
    "path": "README.md",
    "sha": "73dd5b3",
    "source": "GitHub repo description",
    "quote": "A Claude Skill to create an evidence review to inform specific health questions",
    "fetched": "2026-07-29"
  },
  "internal-comms": {
    "name": "internal-comms",
    "url": "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/internal-comms/SKILL.md",
    "sha": "56ea935",
    "source": "SKILL.md description",
    "quote": "A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).",
    "fetched": "2026-07-29"
  },
  "marketingskills": {
    "name": "marketingskills",
    "url": "https://github.com/coreyhaines31/marketingskills",
    "type": "skill",
    "installable": true,
    "repo": "coreyhaines31/marketingskills",
    "ok": true,
    "path": "README.md",
    "sha": "fca9561",
    "source": "GitHub repo description",
    "quote": "Marketing skills for Claude Code and AI agents. CRO, copywriting, SEO, analytics, and growth engineering.",
    "fetched": "2026-07-29"
  },
  "mcp-builder": {
    "name": "mcp-builder",
    "url": "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/mcp-builder/SKILL.md",
    "sha": "8a1a77a",
    "source": "SKILL.md description",
    "quote": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
    "fetched": "2026-07-29"
  },
  "medical-research-skills": {
    "name": "medical-research-skills",
    "url": "https://github.com/aipoch/medical-research-skills",
    "type": "skill",
    "installable": true,
    "repo": "aipoch/medical-research-skills",
    "ok": true,
    "path": "README.md",
    "sha": "8c681cf",
    "source": "GitHub repo description",
    "quote": "Hundreds of agent skills for medical research, including protocol design, data analysis, evidence insights, and academic writing.",
    "fetched": "2026-07-29"
  },
  "medsci-skills": {
    "name": "medsci-skills",
    "url": "https://github.com/Aperivue/medsci-skills",
    "type": "skill",
    "installable": true,
    "repo": "Aperivue/medsci-skills",
    "ok": true,
    "path": "README.md",
    "sha": "6775f30",
    "source": "GitHub repo description",
    "quote": "Agent Skills for medical research — literature search, reporting-guideline & citation checks, statistics, publication figures, submission. Works with Claude Code, Codex, Cursor & GitHub Copilot. Built by a physician-researcher, tested on real publications. MIT.",
    "fetched": "2026-07-29"
  },
  "notebooklm-py": {
    "name": "notebooklm-py",
    "url": "https://github.com/teng-lin/notebooklm-py",
    "type": "skill",
    "installable": true,
    "repo": "teng-lin/notebooklm-py",
    "ok": true,
    "path": "SKILL.md",
    "sha": "b9acbbe",
    "source": "SKILL.md description",
    "quote": "Complete API for Google NotebookLM - full programmatic access including features not in the web UI. Create notebooks, add sources, generate all artifact types, download in multiple formats. Activates on explicit /notebooklm or intent like \"create a podcast about X",
    "fetched": "2026-07-29"
  },
  "pdf": {
    "name": "pdf",
    "url": "https://github.com/anthropics/skills/tree/main/skills/pdf",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/pdf/SKILL.md",
    "sha": "d3e046a",
    "source": "SKILL.md description",
    "quote": "Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rotating pages, adding watermarks, creating new PDFs, filling PDF forms, encrypting/decrypting PDFs, extracting images, and OCR on scanned PDFs to make them searchable. If the user mentions a .pdf file or asks to produce one, use this skill.",
    "fetched": "2026-07-29"
  },
  "planning-with-files": {
    "name": "planning-with-files",
    "url": "https://github.com/OthmanAdi/planning-with-files",
    "type": "skill",
    "installable": true,
    "repo": "OthmanAdi/planning-with-files",
    "ok": true,
    "path": "README.md",
    "sha": "dd18828",
    "source": "GitHub repo description",
    "quote": "Persistent file-based planning for AI coding agents and long-running tasks. Crash-proof markdown plans, session recovery after /clear and compaction, per-turn re-injection against context rot, deterministic completion gate. Manus-style. Claude Code, Codex, Cursor, Kiro, OpenCode and 60+ agents via the Agent Skills standard.",
    "fetched": "2026-07-29"
  },
  "pm-claude-skills": {
    "name": "pm-claude-skills",
    "url": "https://github.com/mohitagw15856/pm-claude-skills",
    "type": "skill",
    "installable": true,
    "repo": "mohitagw15856/pm-claude-skills",
    "ok": true,
    "path": "README.md",
    "sha": "a83c04d",
    "source": "GitHub repo description",
    "quote": "822 professional Agent Skills for Claude, ChatGPT, Gemini, Cursor & Codex — decode a lease, write a PRD, run the AGM, prep the D&D session, practice the salary negotiation. Plain-markdown, MIT, in Anthropic's official plugin directory. Try free in-browser or 'npx pm-claude-skills add'.",
    "fetched": "2026-07-29"
  },
  "pptx": {
    "name": "pptx",
    "url": "https://github.com/anthropics/skills/tree/main/skills/pptx",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/pptx/SKILL.md",
    "sha": "41cd230",
    "source": "SKILL.md description",
    "quote": "Use this skill any time a .pptx or .potx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from any .pptx or .potx file (even if the extracted content will be used elsewhere, like in an email or summary); editing, modifying, or updating existing presentations; combining or splitting slide files; working with templates (.potx), layouts, speaker notes, or comments. Trigger whenever the user mentions \\\"deck,\\\" \\\"slides,\\\" \\\"presentation,\\\" or references a .pptx or .potx filename, regardless of what they plan to do with the content afterward. If a .pptx or .potx file needs to be opened, created, or touched, use this skill.",
    "fetched": "2026-07-29"
  },
  "prompt-master": {
    "name": "prompt-master",
    "url": "https://github.com/nidhinjs/prompt-master",
    "type": "skill",
    "installable": true,
    "repo": "nidhinjs/prompt-master",
    "ok": true,
    "path": "SKILL.md",
    "sha": "85225a6",
    "source": "SKILL.md description",
    "quote": "Generates optimized prompts for AI tools. Activates only when the user explicitly asks to write, fix, improve, or adapt a prompt for a specific AI tool (LLM, Cursor, Midjourney, image AI, video AI, coding agents, etc.). Does not activate for general conversation, coding tasks, document writing, or other non-prompt-engineering work.",
    "fetched": "2026-07-29"
  },
  "scientific-agent-skills": {
    "name": "scientific-agent-skills",
    "url": "https://github.com/K-Dense-AI/scientific-agent-skills",
    "type": "skill",
    "installable": true,
    "repo": "K-Dense-AI/scientific-agent-skills",
    "ok": true,
    "path": "README.md",
    "sha": "4592928",
    "source": "GitHub repo description",
    "quote": "Turn any AI agent into an AI Scientist. The #1 Agent Skills library for science, used by 170,000+ scientists worldwide. 158 ready-to-use skills plus 100+ scientific databases covering biology, chemistry, medicine, and drug discovery. Compatible with Cursor, Claude Code, Codex, Pi, Antigravity, and the open Agent Skills standard.",
    "fetched": "2026-07-29"
  },
  "skill-creator": {
    "name": "skill-creator",
    "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/skill-creator/SKILL.md",
    "sha": "65b3a40",
    "source": "SKILL.md description",
    "quote": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
    "fetched": "2026-07-29"
  },
  "slack-gif-creator": {
    "name": "slack-gif-creator",
    "url": "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/slack-gif-creator/SKILL.md",
    "sha": "16660d8",
    "source": "SKILL.md description",
    "quote": "Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like \"make me a GIF of X doing Y for Slack.",
    "fetched": "2026-07-29"
  },
  "theme-factory": {
    "name": "theme-factory",
    "url": "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/theme-factory/SKILL.md",
    "sha": "90dfcea",
    "source": "SKILL.md description",
    "quote": "Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.",
    "fetched": "2026-07-29"
  },
  "universal-biomedical-skills": {
    "name": "universal-biomedical-skills",
    "url": "https://github.com/mdbabumiamssm/LLMs-Universal-Life-Science-and-Clinical-Skills-",
    "type": "skill",
    "installable": true,
    "repo": "mdbabumiamssm/LLMs-Universal-Life-Science-and-Clinical-Skills-",
    "ok": true,
    "path": "README.md",
    "sha": "ba878dc",
    "source": "README.md (first line)",
    "quote": "_A research-grade Biomedical OS for reproducible, agentic life-science and clinical AI workflows._",
    "fetched": "2026-07-29"
  },
  "web-artifacts-builder": {
    "name": "web-artifacts-builder",
    "url": "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/web-artifacts-builder/SKILL.md",
    "sha": "8b39b19",
    "source": "SKILL.md description",
    "quote": "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.",
    "fetched": "2026-07-29"
  },
  "webapp-testing": {
    "name": "webapp-testing",
    "url": "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/webapp-testing/SKILL.md",
    "sha": "4726215",
    "source": "SKILL.md description",
    "quote": "Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.",
    "fetched": "2026-07-29"
  },
  "xlsx": {
    "name": "xlsx",
    "url": "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    "type": "skill",
    "installable": true,
    "repo": "anthropics/skills",
    "ok": true,
    "path": "skills/xlsx/SKILL.md",
    "sha": "9da5480",
    "source": "SKILL.md description",
    "quote": "Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .xltx, .csv, or .tsv file (e.g., adding columns, computing formulas, formatting, charting, cleaning messy data); create a new spreadsheet from scratch or from other data sources; or convert between tabular file formats. Trigger especially when the user references a spreadsheet file by name or path — even casually (like \\\"the xlsx in my downloads\\\") — and wants something done to it or produced from it. Also trigger for cleaning or restructuring messy tabular data files (malformed rows, misplaced headers, junk data) into proper spreadsheets. The deliverable must be a spreadsheet file. Do NOT trigger when the primary deliverable is a Word document, HTML report, standalone Python script, database pipeline, or Google Sheets API integration, even if tabular data is involved.",
    "fetched": "2026-07-29"
  }
};
