#!/usr/bin/env python3
"""Skill health checks -> skill-health.js (static badge data for the directory).

Objective, offline checks over each skill's real repo. Every badge means a
specific check passed; the badges.html page documents each one. No LLM.

Run:  python3 pipeline/checks.py
"""
import json, re, subprocess, base64, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = pathlib.Path(__file__).resolve().parent / "nodes"
# today is 2026-07-24; "maintained" = pushed on/after this date (12 months back)
MAINTAINED_AFTER = "2025-07-24"

SECRET = re.compile(
    r"(AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{36}|"
    r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|"
    r"""api[_-]?key\s*[:=]\s*['"][A-Za-z0-9_\-]{16,}['"]|xox[baprs]-[A-Za-z0-9-]{10,})""")

# id, label, emoji, one-line meaning (mirrored on badges.html)
CHECKS = [
    ("live_repo",   "Live Repo",    "🔗", "The skill resolves to a real, reachable GitHub repository."),
    ("skill_md",    "SKILL.md",     "📄", "Ships a real skill manifest (SKILL.md), not just a README."),
    ("actionable",  "Actionable",   "⚡", "Has ≥3 machine-followable directives an agent can execute."),
    ("licensed",    "Licensed",     "⚖️", "Has a LICENSE file, so it can be legally imported."),
    ("maintained",  "Maintained",   "🔧", "Pushed within the last 12 months."),
    ("secret_free", "Secret-free",  "🔒", "No hardcoded API keys, tokens, or private keys in the skill file."),
]


def gh_json(path):
    r = subprocess.run(["gh", "api", path], capture_output=True, text=True)
    return json.loads(r.stdout) if r.returncode == 0 else None


def gh_raw(repo, path):
    r = subprocess.run(["gh", "api", f"repos/{repo}/contents/{path}", "--jq", ".content"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None
    try:
        return base64.b64decode(r.stdout).decode("utf-8", "ignore")
    except Exception:
        return None


def cache_of(name):
    f = CACHE / (re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") + ".json")
    return json.loads(f.read_text()) if f.exists() else None


def run_checks(name):
    c = cache_of(name)
    if not c or not c.get("repo"):
        return None
    repo, path = c["repo"], c.get("path", "")
    meta = gh_json(f"repos/{repo}") or {}
    content = gh_raw(repo, path) or ""
    results = {
        "live_repo": bool(meta.get("full_name")),
        "skill_md": path.lower().endswith("skill.md"),
        "actionable": len(c.get("nodes", [])) >= 3,
        "licensed": bool(meta.get("license")),
        "maintained": (meta.get("pushed_at", "") >= MAINTAINED_AFTER),
        "secret_free": not bool(SECRET.search(content)),
    }
    passed = sum(results.values())
    if results["live_repo"] and results["secret_free"] and passed == 6:
        tier = "gold"
    elif results["live_repo"] and results["secret_free"] and passed >= 4:
        tier = "silver"
    elif results["live_repo"] and results["secret_free"]:
        tier = "bronze"
    else:
        tier = "unrated"
    return {"tier": tier, "repo": repo, "passed": passed, "total": 6,
            "checks": [{"id": cid, "label": lbl, "emoji": em, "meaning": meaning, "pass": results[cid]}
                       for cid, lbl, em, meaning in CHECKS]}


def all_cached_skills():
    """Every skill with a node cache (the full directory, minus repo-less ones)."""
    return sorted(json.loads(f.read_text())["name"] for f in CACHE.glob("*.json"))


def main():
    names = all_cached_skills()
    print(f"Checking {len(names)} skills:\n")
    health = {}
    for name in names:
        res = run_checks(name)
        if not res:
            print(f"  ⊘ {name:32s} — no cache/repo, skipped")
            continue
        health[name] = res
        chips = " ".join(c["emoji"] for c in res["checks"] if c["pass"])
        print(f"  {res['tier']:7s} {name:32s} {res['passed']}/6  {chips}")

    js = ("// AUTO-GENERATED by pipeline/checks.py — skill health badge data.\n"
          "const SKILL_HEALTH = " + json.dumps(health, ensure_ascii=False) + ";\n"
          'if (typeof window !== "undefined") { window.SKILL_HEALTH = SKILL_HEALTH; }\n')
    (ROOT / "skill-health.js").write_text(js)
    tiers = {}
    for h in health.values():
        tiers[h["tier"]] = tiers.get(h["tier"], 0) + 1
    print(f"\nwrote skill-health.js: {len(health)} skills — {tiers}")


if __name__ == "__main__":
    main()
